---
# If not running locally then set value so as not linked from tmp
roles_path_exposed: "{{ role_path }}"
home_path: "/home/"
username: "vagrant"
git_user: "vagrant"
git_email: "vagrant@vagrant.com"
