---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  roles_path: ../../roles
  playbook: test/integration/playbook.yml
  ansible_inventory: test/integration/hosts.ini

verifier:
  name: inspec

platforms:
  - name: generic/fedora32
    provisioner:
      extra_vars:
        # This is used by the kitchen role, sole purpose is to sync this repository to vm
        home_path: '/home/'
        username: 'vagrant'

suites:
  - name: fedora
