- name: Check ~/.sdkman directory exists
  stat:
    path: ~/.sdkman
  register: sdk_directory

- name: Download SDK man
  remote_user: packages.install_user
  shell: curl -s "https://get.sdkman.io" | bash
  when: sdk_directory.stat.exists == False
  args:
    warn: no

- name: Install sdkman
  remote_user: packages.install_user
  shell: source "$HOME/.sdkman/bin/sdkman-init.sh"
  when: sdk_directory.stat.exists == False
  args:
    warn: no
