---
- name: "check {{ name }} is installed" 
  ansible.builtin.stat:
    path: "{{ path }}/{{ name }}" 
  register: file

- name: "check {{ name }} version" 
  command: "{{ name }} {{ version_cmd }}" 
  register: version_stat
  when: "file.stat.exists"
  changed_when: False
  failed_when: False

- name: "Remove outdated package {{ name }}" 
  ansible.builtin.file:
    dest: "{{ path }}/{{ name }}" 
    state: absent
  when: 
    - file.stat.exists
    - version not in version_stat.stdout

- name: "Get package"
  block:

  - name: "Download {{ name }}"
    unarchive:
      src: "{{ src }}"
      dest: /tmp
      remote_src: yes

  - name: "Copy {{ name }} to {{ path }}" 
    copy:
      remote_src: True
      src: "/tmp/{{ extracted_path }}"
      dest: "{{ path }}/{{ name }}" 
      owner: root
      group: root
      mode: +x

  when: "not file.stat.exists or version not in version_stat.stdout"
