---
- name: all
  hosts: all
  roles:
    # Provisions required terminal tooling
    - { role: terminal-tools, tags: ['terminal'] }
    # Provisions desktop gui apps
    - { role: desktop, tags: ['desktop'] }
    # My dotfiles live here
    - { role: dotfiles, tags: ['dotfiles'] }
    # Installs neovim and testing tooling
    - { role: nvim, tags: ['nvim'] }
    # Most of what follows is required for devops
    - { role: chef-workstation, tags: ['chef', 'provisioning'] }
    - { role: ruby, tags: ['ruby', 'rvm'] }
    # - { role: sdkman, tags: ['sdkman', 'java'] }
    - { role: go, tags: ['go'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: ansible, tags: ['ansible', 'provisioning'] }
    - { role: packer, tags: ['packer'] }
    - { role: gcloud-sdk, tags: ['gcloud-sdk'] }
    - { role: azure-functions-core-tools, tags: ['azure-function-core-tools'] }
    - { role: influxdb-cli, tags: ['influxdb-cli', 'database'] }
    - { role: kubectl, tags: ['kubectl', 'contianers'] }
    - { role: helm, tags: ['helm'] }
    - { role: notary, tags: ['notary'] }
    - { role: minikube, tags: ['minikube'] }
    - { role: docker, tags: ['docker'] }
    - { role: k9s, tags: ['k9s', 'contianers'] }
    - { role: terraform, tags: ['terraform', 'provisioning'] }

