---
- name: all
  hosts: all
  roles:
    # Provisions required terminal tooling
    - { role: terminal-tools, tags: ['terminal'] }
    # Provisions desktop gui apps
    - { role: desktop, tags: ['desktop'] }
    # My dotfiles live here
    - { role: dotfiles, tags: ['dotfiles'] }
    # Installs neovim and testing tooling
    - { role: nvim, tags: ['nvim'] }
    # Most of what follows is required for devops
    - { role: chef-workstation, tags: ['chef'] }
    - { role: ruby, tags: ['ruby', 'rvm'] }
    - { role: sdkman, tags: ['sdkman'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: ansible, tags: ['ansible'] }
    - { role: packer, tags: ['packer'] }
    - { role: gcloud-sdk, tags: ['gcloud-sdk'] }
    - { role: influxdb-cli, tags: ['influxdb-cli'] }
    - { role: kubectl, tags: ['kubectl'] }
    - { role: helm, tags: ['helm'] }
    - { role: k9s, tags: ['k9s'] }
    - { role: terraform, tags: ['terraform'] }

