---
- name: all
  hosts: all
  roles:
    - { role: chef-workstation, tags: ['chef'] }
    - { role: ruby, tags: ['ruby', 'rvm'] }
    - { role: ssh, tags: ['chrome'] }
    - { role: chrome, tags: ['chrome'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: nvim, tags: ['nvim'] }
    - { role: slack, tags: ['slack'] }
    - { role: ansible, tags: ['ansible'] }
    - { role: gcloud-sdk, tags: ['gcloud-sdk'] }

