- name: Install ubuntu packages
  import_tasks: ubuntu.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Install osx packages
  import_tasks: osx.yml
  when: ansible_facts['os_family'] == "Darwin"

- name: Install npm global packages
  npm:
    name: "{{ item }}"
    global: yes
  loop: "{{ npm.packages.global }}"

- name: Install gem global
  gem:
    name: "{{ item }}"
    user_install: false
  loop: "{{ gem.packages }}"
