---
# tasks file for ubuntu_packages
- name: Install snap classic packages
  shell: >
    snap list | grep -E '^{{ item }}'
    && echo 'Already installed.'
    || snap install --classic '{{ item }}'
  loop: "{{ snap_packages.classic }}"
  register: snap_result
  changed_when: "'Already installed.' not in snap_result.stdout"
  become: yes

- name: Setup additional apt keys
  apt_key:
    url: "{{ item }}"
    state: present
  loop: "{{ apt_keys }}"
  become: yes

- name: Setup additional apt sources
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ apt_sources }}"
  become: yes

- name: Install apt packages
  apt:
    name: "{{ item }}"
  loop: "{{ apt_packages }}"
  become: yes

# As of ansible 2.8 can do this...
# - name: Install snap classic packages
#   snap:
#     name: "{{ item.name | default(item) }}"
#     classic: yes
#   loop: "{{ snap_packages.packages.classic }}"

# Set up local directory for global npm packages due to permissions
- name: Ensure ~/.npm-global directory exists
  file:
    path: "~/.npm-global"
    state: directory

- name: configure npm to use path
  shell: npm config set prefix '~/.npm-global'

# rbenv installed via apt returns a different set of versions
# and 2.5.1 is not available, so install the old way

- name: Install rbenv via script
  remote_user: packages.install_user
  shell: >
    which rbenv && echo 'Already installed.' ||
    curl -sL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash -
  register: rbenv_result
  changed_when: "'Already installed.' not in rbenv_result.stdout"
  failed_when: rbenv_result.rc > 1

- name: Download go 1.12.7
  unarchive:
    src: https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
  become: yes
