---
# tasks file for ubuntu_packages
- name: Install snap classic packages
  shell: >
    snap list | grep -E '^{{ item }}'
    && echo 'Already installed.'
    || snap install --classic '{{ item }}'
  loop: "{{ snap_packages.classic }}"
  register: snap_result
  changed_when: "'Already installed.' not in snap_result.stdout"
  become: yes

- name: Install apt packages
  apt:
    name: "{{ item }}"
  loop: "{{ apt_packages }}"
  become: yes

# As of ansible 2.8 can do this...
# - name: Install snap classic packages
#   snap:
#     name: "{{ item.name | default(item) }}"
#     classic: yes
#   loop: "{{ snap_packages.packages.classic }}"

# Set up local directory for global npm packages due to permissions
- name: Ensure ~/.npm-global directory exists
  file:
    path: "~/.npm-global"
    state: directory

- name: configure npm to use path
  shell: npm config set prefix '~/.npm-global'
