---
- name: Create ~/.config directory if it does not exist
  file:
    path: "~/.config"
    state: directory
    mode: '0755'

- name: Creates the .gitconfig file
  template:
    src: gitconfig.j2
    dest: "~/.gitconfig"
    mode: 0644

- name: Create a symbolic ~/.config/git for hooks
  file:
    src: '{{roles_path_exposed}}/files/git'
    dest: '~/.config/git'
    state: link

