---
- name: "Create {{ home_path }}/{{ username }}/.config directory if it does not exist"
  file:
    path: "{{ home_path }}/{{ username }}/.config"
    state: directory
    mode: '0755'

- name: Creates the .gitconfig file
  template:
    src: gitconfig.j2
    dest: "{{ home_path }}/{{ username }}/.gitconfig"
    mode: 0644

- name: "Create a symbolic {{ home_path }}/{{ username }}/.config/git for hooks"
  file:
    src: '{{ roles_path_exposed }}/files/git'
    dest: '{{ home_path }}/{{ username }}/.config/git'
    state: link

