---
- name: Gather the apt package facts
  package_facts:
    manager: apt
  when: ansible_facts.packages is not defined

- name: Add gcloud-sdk GPG apt Key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

# This fails due to ansible apt source that is incorrect, deleted it then ran fine
# /etc/apt/sources.list.d/ansible-ubuntu-ansible-groovy.list
- name: Add gcloud-sdk Repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.cloud.google.com/apt cloud-sdk main
    
- name: Install google-cloud-sdk
  package:
    name: google-cloud-sdk
  when: "'google-cloud-sdk' not in ansible_facts.packages"
