---
- stat:
    path: /usr/local/bin/packer
  register: file

- name: Download and extract packer
  unarchive:
    src: https://releases.hashicorp.com/packer/1.6.1/packer_1.6.1_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
  when: not file.stat.exists
