---
- stat:
    path: /usr/local/bin/packer
  register: file

- name: Download and extract packer
  unarchive:
    src: "https://releases.hashicorp.com/packer/{{ packer.version }}/packer_{{ packer.version }}_linux_amd64.zip"
    dest: /usr/local/bin
    remote_src: yes
  when: not file.stat.exists

- name: Gather the apt package facts
  package_facts:
    manager: apt
  when: ansible_facts.packages is not defined
