---
- name: Gather the apt package facts
  package_facts:
    manager: apt
  when: ansible_facts.packages is not defined

# Used to build headers for virtualbox, required by kitchen
- name: "Install virtual box required packages"
  package:
    name: "{{ item }}"
  when: item not in ansible_facts.packages
  loop:
    - gcc
    - make
    - perl

- name: "Install vagrant version: {{ vagrant.version }}"
  package:
    name: "vagrant={{ vagrant.version }}"
  when: "'vagrant' not in ansible_facts.packages"

- name: "Install virtualbox version: {{ virtualbox.version }}"
  package:
    name: "virtualbox={{ virtualbox.version }}"
  when: "'virtualbox' not in ansible_facts.packages"

# - name: "Install virtualbox guest additions"
#   package:
#     name: "virtualbox-guest-additions"
#   when: "'virtualbox-guest-additions' not in ansible_facts.packages"

- name: "Install chef 3.3.23"
  ansible.builtin.apt:
    deb: "https://packages.chef.io/files/stable/chefdk/3.3.23/ubuntu/18.04/chefdk_3.3.23-1_amd64.deb"
  when: "'chefdk' not in ansible_facts.packages"
