---
- name: Gather the rpm package facts
  package_facts:
    manager: rpm
  when: ansible_facts.packages is not defined

# Used to build headers for virtualbox, required by kitchen
- name: "Install virtual box headers required packages"
  package:
    name: "{{ item }}"
  when: item not in ansible_facts.packages
  loop:
    - gcc
    - make
    - perl

- name: "Install vagrant version: {{ vagrant.version }}"
  package:
    name: "vagrant-{{ vagrant.version }}"
  when: "'vagrant' not in ansible_facts.packages"

- name: Capture stat of virtualbox repository file
  stat:
    path: "/etc/yum.repos.d/virtualbox.repo"
  register: virtualbox_repo

- name: "Download virtualbox repository file"
  get_url:
    url: "http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo"
    dest: "/etc/yum.repos.d/virtualbox.repo"
    mode: '0644'
  when: not virtualbox_repo.stat.exists

# Ansible doesn't like checking if a string+variable is in a fact so create single fact and check that is in another fact below
- name: "Create virtualbox version fact"
  set_fact:
    virtualbox_version: "VirtualBox-{{ virtualbox.version }}"

- name: "Install virtualbox version: {{ virtualbox.version }}"
  package:
    name: "{{ virtualbox_version }}"
  when: "virtualbox_version not in ansible_facts.packages"

- name: "Install virtualbox guest additions"
  package:
    name: "virtualbox-guest-additions"
  when: "'virtualbox-guest-additions' not in ansible_facts.packages"

- name: "Install chef 3.3.23"
  yum:
    name: "https://packages.chef.io/files/stable/chefdk/3.3.23/el/7/chefdk-3.3.23-1.el7.x86_64.rpm"
  when: "'chefdk' not in ansible_facts.packages"
