---
# tasks file for snap_packages
- name: Install snap classic packages
  shell: >
    snap list | grep -E '^{{ item }}'
    && echo 'Already installed.'
    || snap install --classic '{{ item }}'
  loop: "{{ snap_packages.packages.classic }}"
  register: snap_result
  changed_when: "'Already installed.' not in snap_result.stdout"
  become: yes

# As of ansible 2.8 can do this...
# - name: Install snap classic packages
#   snap:
#     name: "{{ item.name | default(item) }}"
#     classic: yes
#   loop: "{{ snap_packages.packages.classic }}"
