---
# tasks file for zsh
# Note that this assumes ZSH has been installed by either packages role

- name: check if oh my zsh installed
  command: ls ~/.oh-my-zsh
  register: oh_my_zsh_installed
  ignore_errors: yes
  changed_when: false

- name: Install oh_my_zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  when: "'No such file or directory' in oh_my_zsh_installed.stderr"

- name: Create zsh config file
  copy:
    src: files/zshrc
    dest: "~/.zshrc"
    mode: 0644

# Install teamocil for automating tmux sessions
# https://github.com/remiprev/teamocil
- gem:
    name: teamocil
    user_install: false

- name: Ensure ~/.teamocil directory exists
  file:
    path: "~/.teamocil"
    state: directory

- name: Copy ~/.teamocil directory
  copy:
    src: files/teamocil/
    dest: "~/.teamocil"
    mode: 0644
