---
- stat:
    path: /usr/local/bin/gron
  register: file

- name: Download gron
  unarchive:
    src: "https://github.com/tomnomnom/gron/releases/download/v{{ gron.version }}/gron-linux-amd64-{{ gron.version }}.tgz"
    dest: /tmp
    remote_src: yes
  when: not file.stat.exists

- name: Copy gron to /usr/local/bin
  copy:
    src: /tmp/gron
    dest: /usr/local/bin/gron
    owner: root
    group: root
    mode: +x
  when: not file.stat.exists
