---
- name: Enable lazygit repo
  command:
    cmd: add-apt-repository ppa:lazygit-team/release
    creates: /etc/apt/sources.list.d/lazygit-team-ubuntu-release-groovy.list

- name: Gather the apt package facts
  package_facts:
    manager: apt
  when: ansible_facts.packages is not defined

- name: Install LazyGit
  package:
    name: lazygit
  when: "'lazygit' not in ansible_facts.packages"

