---
- name: Gather the apt package facts
  package_facts:
    manager: apt
  when: ansible_facts.packages is not defined

- name: "Install slack"
  apt:
    deb: "https://downloads.slack-edge.com/linux_releases/slack-desktop-4.13.0-amd64.deb"
  when: "'slack' not in ansible_facts.packages"
