---
# tasks file for atom
- name: Install atom packages using apm
  remote_user: atom.install_user
  shell: >
    apm list --bare | grep -E '^{{ item }}@'
    && echo 'Already installed.'
    || apm install '{{ item }}'
  loop: "{{ atom.packages }}"
  register: apm_result
  changed_when: "'Already installed.' not in apm_result.stdout"

- name: Ensure ~/.atom directory exists
  file:
    path: "~/.atom"
    state: directory

- name: Create atom config file
  copy:
    src: files/config.cson
    dest: "~/.atom/config.cson"
    mode: 0644
