---
- name: Gather the apt package facts
  package_facts:
    manager: apt
  when: ansible_facts.packages is not defined

- name: Install ansible
  package:
    name: ansible
  when: "'ansible' not in ansible_facts.packages"

- name: Install python3-pip
  package:
    name: python3-pip
  when: "'python3-pip' not in ansible_facts.packages"

- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3

- name: Install ansible-lint
  pip:
    name: ansible-lint
    virtualenv: '{{ ansible_repo_home }}/venv'
