---
# tasks file for terminal
- name: Run ubuntu specific steps
  import_tasks: ubuntu.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Run osx specific steps
  import_tasks: osx.yml
  when: ansible_facts['os_family'] == "Darwin"

- name: Creates the .gitconfig file
  template:
    src: .gitconfig.j2
    dest: "~/.gitconfig"
    mode: 0644

- name: Ensure ~/.vim/colors directory exists
  file:
    path: "~/.vim/colors"
    state: directory

- name: Download solarized vim colours
  get_url:
    url: https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim
    dest: "~/.vim/colors/solarized.vim"

- name: Create .vimrc
  copy:
    src: files/.vimrc
    dest: "~/.vimrc"
    mode: 0644
