---
# tasks file for terminal
- name: Create a symbolic link for ~/.bash_profile
  file:
    src: '{{ playbook_dir }}/roles/terminal/files/bash_profile'
    dest: '~/.bash_profile'
    state: link

- name: Create a symbolic link for ~/.bashrc.d
  file:
    src: '{{ playbook_dir }}/roles/terminal/files/bashrc.d'
    dest: '~/.bashrc.d'
    state: link

- name: Run ubuntu specific steps
  import_tasks: ubuntu.yml
  when: ansible_facts['os_family'] == "Debian"

#- name: Run osx specific steps
#  import_tasks: osx.yml
#  when: ansible_facts['os_family'] == "Darwin"

- name: Setup tmux settings
  import_tasks: tmux.yml

- name: Creates the .gitconfig file
  template:
    src: gitconfig.j2
    dest: "~/.gitconfig"
    mode: 0644

- name: Create symbolic link of .ackrc
  file:
    src: '{{ playbook_dir }}/roles/terminal/files/ackrc'
    dest: '~/.ackrc'
    state: link
