---
# tasks file for terminal

- set_fact: home_dir="/home"
  when: ansible_facts['os_family'] == "Debian"

- set_fact: home_dir="/Users"
  when: ansible_facts['os_family'] == "Darwin"

- name: Create .terminal
  copy:
    src: files/.bash_profile
    dest: "{{ home_dir }}/{{ terminal.install_user }}/.bash_profile"
    mode: 0644

- name: Copy ubuntu .bashrc.d directory
  copy:
    src: files/ubuntu-.bashrc.d
    dest: "{{ home_dir }}/{{ terminal.install_user }}"
    mode: 0644
  when: ansible_facts['os_family'] == "Debian"

- name: Copy OSX .bashrc.d directory
  copy:
    src: files/osx-.bashrc.d
    dest: "{{ home_dir }}/{{ terminal.install_user }}"
    mode: 0644
  when: ansible_facts['os_family'] == "Darwin"

- name: Creates the .gitconfig file
  template:
    src: .gitconfig.j2
    dest: "{{ home_dir }}/{{ terminal.install_user }}/.gitconfig"
    mode: 0644
