# This is simply used when testing with kitchen to copy roles to expected location, useful for checking symlinks etc
---
- name: Creates the ansible directory
  file:
    path: ~/personnal-workspace/ansible
    state: directory
  become: true
  become_user: vagrant

  # The copy task is slow when you have many files, using sync is much faster
- name: Copy ansible code to target
  synchronize:
    src: "{{ role_path }}/../../roles"
    dest: "{{ home_path }}/vagrant/personnal-workspace/ansible/"
    # Hack to set user as become isn't honoured
    ssh_args: "['-l vagrant', '--exclude=**/.kitchen']"

- name: Creates the vim directory
  file:
    path: ~/personnal-workspace/vim-environment
    state: directory
  become: true
  become_user: vagrant

- name: Copy fake vim config directory contents
  synchronize:
    src: "{{ role_path }}/../../roles/nvim/test/integration/fake-nvim-env/"
    dest: "{{ home_path }}/vagrant/personnal-workspace/vim-environment"
    ssh_args: "-l vagrant"
