# https://fedoramagazine.org/docker-and-fedora-32/
---
- name: Check if systemd.unified_cgroup_hierarchy=0 is set in kernelopts
  command: grep -Eq '^kernelopts=.* systemd\.unified_cgroup_hierarchy=0' /boot/grub2/grubenv
  register: grubenv_has_cgroup_exception
  check_mode: no
  ignore_errors: yes
  changed_when: no

- name: Enable old cgroups
  command: grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
  when:
    - grubenv_has_cgroup_exception.rc != 0

- name: Install moby
  package:
    name: moby-engine

- name: Docker Compose
  package:
    name: docker-compose

- name: Enable moby/docker
  service:
    name: docker
    enabled: yes

- name: Create docker group
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: yes

- firewalld:
    interface: docker0
    zone: trusted
    permanent: true
    state: enabled

- firewalld:
    masquerade: true
    zone: FedoraWorkstation
    permanent: true
    state: enabled
