---
- name: Gather the apt package facts
  package_facts:
    manager: apt
  when: ansible_facts.packages is not defined

- name: "Install docker dependencies"
  package:
    name: "{{ item }}"
  when: item not in ansible_facts.packages
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- shell: lsb_release -cs
  register: release

# This fails due to ansible apt source that is incorrect, deleted it then ran fine
# /etc/apt/sources.list.d/ansible-ubuntu-ansible-groovy.list
- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ release.stdout }} stable"
    
- name: Install docker
  package:
    name: "{{ item }}"
  when: item not in ansible_facts.packages
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
