---
# tasks file for ubuntu_packages
- name: Install apt packages
  apt:
    name: "{{ item }}"
  loop: "{{ vim.apt_packages }}"
  become: yes

# Set up local directory for global npm packages due to permissions
- name: Ensure ~/.npm-global directory exists
  file:
    path: "~/.npm-global"
    state: directory

- name: configure npm to use path
  shell: npm config set prefix '~/.npm-global'

- name: Download go 1.12.7
  unarchive:
    src: https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
  become: yes
