---
- stat:
    path: /opt/azure-function
  register: stat

- file:
    path: /opt/azure-function
    owner: root
    group: root
    state: directory

- name: Download Azure Functions Core Tools
  unarchive:
    src: "https://github.com/Azure/azure-functions-core-tools/releases/download/{{ afct.version }}/Azure.Functions.Cli.linux-x64.{{ afct.version }}.zip"
    dest: /opt/azure-function
    remote_src: yes
  when: not stat.stat.exists

- name: Set ownership and permissions of func
  file:
    path: /opt/azure-function/func
    owner: root
    group: root
    mode: +x

- name: Symlink func
  file:
    src: /opt/azure-function/func
    dest: /usr/local/bin/func
    owner: root
    group: root
    state: link

- name: Set ownership and permissions of gozip
  file:
    path: /opt/azure-function/gozip
    owner: root
    group: root
    mode: +x

- name: Symlink func
  file:
    src: /opt/azure-function/gozip
    dest: /usr/local/bin/gozip
    owner: root
    group: root
    state: link
